name: Build AI Agent EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole main.py
      # Change "main.py" if your entry file name is different

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ARIA.exe
        path: dist/*.exe
