name: Test Hello World EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller colorama
          
      - name: Test Python script
        run: python hello_world.py --version
        continue-on-error: true
        
      - name: Build Hello World EXE
        run: |
          pyinstaller --onefile --windowed --name "ARIA-HelloWorld" hello_world.py
          
      - name: Verify build
        run: |
          dir dist
          if (Test-Path "dist/ARIA-HelloWorld.exe") {
            echo "✅ Build successful! EXE file created."
            $size = (Get-Item "dist/ARIA-HelloWorld.exe").Length
            echo "📦 File size: $([math]::Round($size/1MB, 2)) MB"
          } else {
            echo "❌ Build failed! EXE file not found."
            exit 1
          }
        shell: powershell
        
      - name: Upload Hello World EXE
        uses: actions/upload-artifact@v3
        with:
          name: ARIA-HelloWorld.exe
          path: dist/ARIA-HelloWorld.exe
